### ISSUE TITLE
I encountered a little problem when modifying data locally, please help

### ISSUE THREAD

**Issue by crmsci** [KarmaBlackshaw/baccarat-roadmap#1]
Hello, I’m sorry to bother you. I’m learning Vue code recently. I downloaded your code and ran it on my computer. I encountered this problem. I already have data on the Internet, and I only sent it to Zhuang Xian and San A result is sent to the web page without manual processing. How to write code?
thanks for your answer
![20230301165942](https://user-images.githubusercontent.com/8220556/222091989-b98d8fc4-06a0-48d6-868f-1409eaa2043b.png)

**Comment by KarmaBlackshaw** [comment]
hey @crmsci, I'm not quite I understood your query. What code would you like to write?

**Comment by crmsci** [comment]
![20230301190226](https://user-images.githubusercontent.com/8220556/222121456-13e8ee60-144f-44b3-a4e0-54d0a7b2cb73.png)
Similar to this, the road map will be displayed by direct api request, instead of clicking the button yourself.

**Comment by crmsci** [comment]
https://github.com/qeshion2104/baccarat-road-calculator
I refer to this, but this is randomly generated. I want to change it to request interface data. The data of the data interface is like this, "BPPBBBBBBBBBBBBBBBPBBBBBBBPBBPPPPPPBBBBPPBPPBBBBBPBPPTPPPBPPBTPBBPP", directly return to the roadmap

**Comment by KarmaBlackshaw** [comment]
I see, you can check my fetch the data from the API, you can use the utility to generate the roadmaps. It should be located here:

https://github.com/KarmaBlackshaw/baccarat-roadmap/blob/master/src/views/home/Home.vue
